name = "bbchallenge"
defaultTargets = ["Antihydra"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.29.0-rc8"

[[lean_lib]]
name = "BusyLean"
srcDir = "BusyLean"

[[lean_lib]]
name = "Antihydra"
srcDir = "Antihydra"

[[lean_lib]]
name = "Cryptid"
srcDir = "Cryptid"

[[lean_lib]]
name = "TM5"
srcDir = "1RB---0RB0LA2RA_2LB2LA3RA4LB0LB"
roots = ["Basics", "machine", "BackwardTrace", "Dio", "Probabilistic"]

[[lean_lib]]
name = "Sweeper"
srcDir = "1RB1LA_1RC0RF_1RD---_0LE1RB_---0LA_1LD1RF"
roots = ["machine"]

[[lean_lib]]
name = "Pillai"
srcDir = "1RB1LA_1RC1RE_1LD0RB_1LA0LC_0RF0RD_0RB---"
roots = ["BakerWustholz", "RatHeight", "Ellison", "Pomme", "Hensel", "machine", "Bootstrap"]

[[lean_lib]]
name = "ParityBouncer"
srcDir = "1RB1RF_1LC1LF_0RE1LD_0LB1LD_---1RC_1RA0RD"
roots = ["machine"]

[[lean_lib]]
name = "BMO1"
srcDir = "1RB1RE_1LC0RA_0RD1LB_---1RC_1LF1RE_0LB0LE"
roots = ["machine"]

[[lean_lib]]
name = "Chaotic6"
srcDir = "1RB1LD_1RC0LE_1LA1RE_0LF1LA_1RB0RB_---0LB"
roots = ["machine"]

[[lean_lib]]
name = "Shifty6"
srcDir = "1RB1LA_0LC0RC_1LE1RD_1RE1RC_1LF0LA_---1LE"
roots = ["machine"]

[[lean_lib]]
name = "LucysMoonlight"
srcDir = "1RB0RD_0RC1RE_1RD0LA_1LE1LC_1RF0LD_---0RA"
roots = ["machine"]

[[lean_lib]]
name = "Counter6"
srcDir = "1RB1RA_0RC1RC_1LD0LF_0LE1LE_1RA0LB_---0LC"
roots = ["machine"]
