name = "bbchallenge"
defaultTargets = ["Antihydra"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "BusyLean"
srcDir = "BusyLean"

[[lean_lib]]
name = "Antihydra"
srcDir = "Antihydra"

[[lean_lib]]
name = "Cryptid"
srcDir = "Cryptid"

[[lean_lib]]
name = "TM5"
srcDir = "1RB---0RB0LA2RA_2LB2LA3RA4LB0LB"
roots = ["machine"]
