import Mathlib.Data.Nat.Basic
import Mathlib.Data.Nat.Log
import Mathlib.Data.Rat.Defs
import Mathlib.Tactic.NormNum
import Dio

/-!
# Probabilistic.lean — a probabilistic model for the bad-state condition

This file builds a probabilistic sanity-check for nonhalting. It is a
HEURISTIC model, not a rigorous proof. The model treats the binary value
`V_i` at each era as uniformly random in `[0, 2^{n_i})` conditional on the
trajectory having reached era `i`. We then compute:

1. Whether any `V ∈ [0, 2^n)` makes `V + 2^n + 3^d` a power of 2 for the
   specific `(n, d)` of the era (`hasBadV n d`).
2. The conditional probability that a uniformly-random `V` hits the bad
   value: `1/2^n` if `hasBadV`, else `0`.
3. The "never hit bad" probability up to era `N`.

## IMPORTANT: dependency on heuristic (and disproved) branches of `nextEra`

All era-sequence results here depend on `Dio.nextEra`. Only its **k=0**
branch is rigorously backed by `machine.overflow_odd`; the **k=1** and
**k≥2** branches are heuristic approximations (see `Dio.lean` §3a and
`strategy.md`):

- **k=1 branch** collapses a multi-step composition
  (`overflow_odd_k1` → `cycle_nonzero` → second odd overflow) into a
  single closed form; this is not faithful in general.
- **k≥2 branch** uses `V_new = (V_end - 1)/2`, a guess consistent with
  macro.md's era 2 but **disproved in general** by simulation — for
  `(V=11, n=4, d=2)` the TM actually reaches `(V=56, n=6, d=7)` after
  1152 steps, not the `(V=6, n=3, d=4)` the formula predicts.

In the first 22 arithmetic eras computed here, non-k=0 branches are
invoked at:

    Era 2 → Era 3  (V_end = 2851, V_end mod 4 = 3, k≥2 heuristic)
    Era 6 → Era 7  (k=1 heuristic)
    Era 7 → Era 8  (k=1 heuristic)
    Era 8 → Era 9  (k≥2 heuristic)
    ...etc.

Therefore:

- **Eras 0, 1, 2** (values `(2,2,4), (12,5,6), (131,8,8)`) are
  rigorously the TM's actual era entries, because they are reached using
  only the k=0 odd-overflow branch (formalized as `overflow_odd` in
  `machine.lean`).

- **Eras 3+** depend on the heuristic k=1 or k≥2 branches. As a
  statement about the arithmetic sequence `eraSeq`, they are true
  (verified by `native_decide`); as a statement about the TM's
  trajectory, they are NOT reliable.

The facts proved in this file are computational facts about the
arithmetic function `eraSeq` (which is well-defined by its code). They
only *correspond* to TM behavior through the (currently-false)
`arith_reachable_iff_TM` bridge in `Dio.lean`, which would require
corrected k=1 and k≥2 branches.

## What the computational results actually say

- For the first 21 arithmetic era-entries `(V_i, n_i, d_i)` generated by
  `nextEra` from `E0`, `hasBadV n_i d_i = false`. This is a hard
  structural fact about the specific numeric sequence: no power of 2
  lies in `[2^{n_i} + 3^{d_i}, 2^{n_i+1} + 3^{d_i})`.

- Era 21 is the first where `hasBadV = true`. At that era `n_21 = 68`,
  so under the uniform-V model `P(era 21 is bad | reached era 21) ≤
  1/2^{68} ≈ 3.4·10^-21`.

- Transfer to the TM: the arithmetic sequence from era 3 onward is
  NOT known to equal the TM's trajectory (the heuristic k=1 and k≥2
  branches of `nextEra` are not proved faithful — see
  `strategy.md`). So the "first 21 eras avoid bad" claim is about the
  arithmetic sequence only, not the TM.

## Status

Purely heuristic. The trajectory is deterministic: the actual `V_i` is not
random. But:
- If *any* V_i in era `i` were `badV(n_i, d_i)`, the TM would halt at that
  era.
- The probability of this happening under uniform random V is astronomically
  small for this specific arithmetic sequence.
- This gives weak circumstantial evidence for C.3 and nonhalting —
  **contingent on a corrected `nextEra`** whose k=1 and k≥2 branches
  faithfully model the TM.
-/

set_option autoImplicit false

namespace TM5.Prob

open TM5.Dio

-- ============================================================
-- §1. Bad-V characterization
-- ============================================================

/-- The smallest `m` with `2^m ≥ lo`. Uses `Nat.log` to compute. -/
def smallestPow (lo : Nat) : Nat :=
  let m := Nat.log 2 lo
  if 2^m ≥ lo then m else m + 1

/-- Does there exist a "bad" `V ∈ [0, 2^n)` making `V + 2^n + 3^d` a
    power of 2? Equivalent to: some power of 2 lies in
    `[2^n + 3^d, 2^(n+1) + 3^d)`. -/
def hasBadV (n d : Nat) : Bool :=
  let lo := 2^n + 3^d
  let hi := 2^(n+1) + 3^d
  let m := smallestPow lo
  decide (2^m < hi)

/-- The unique bad `V` in `[0, 2^n)` if it exists, else `none`. -/
def badV (n d : Nat) : Option Nat :=
  let lo := 2^n + 3^d
  let hi := 2^(n+1) + 3^d
  let m := smallestPow lo
  if 2^m < hi then some (2^m - 2^n - 3^d) else none

-- Sanity check: at era 21 (n=68, d=46), the bad V is concretely computed
example : badV 68 46 = some 286646940907436505607 := by native_decide

-- ============================================================
-- §2. Per-era probability
-- ============================================================

/-- Probability that a uniformly-random `V ∈ [0, 2^n)` is bad at era `(n, d)`. -/
def probBad (n d : Nat) : Rat :=
  if hasBadV n d then (1 : Rat) / (2^n : Nat) else 0

/-- Survival probability at era `(n, d)`: `1 - probBad`. -/
def probSurvive (n d : Nat) : Rat := 1 - probBad n d

-- ============================================================
-- §3. Trajectory analysis
-- ============================================================

/-- Extract the `(n, d)` of the i-th era from `eraSeq` (or `none` if halted). -/
def eraND (i : Nat) : Option (Nat × Nat) :=
  (eraSeq i).map (fun ⟨_, n, d⟩ => (n, d))

/-- Pointwise `hasBadV` for each era `i` in the trajectory. -/
def eraHasBadV (i : Nat) : Bool :=
  match eraND i with
  | some (n, d) => hasBadV n d
  | none => false  -- trajectory halted; no era

-- ============================================================
-- §4. Concrete computations for the first many eras
-- ============================================================

/-!
### Rigorous results (independent of the k≥2 conjecture)

The first 3 arithmetic era entries `(V_i, n_i, d_i)` for i ∈ {0, 1, 2} use
only the k=0 branch of `nextEra` (and the initial state `E0`). Since the
k=0 branch is backed by the formalized theorem `overflow_odd` in
`machine.lean`, these era entries equal the TM's actual era entries
unconditionally.
-/

/-- Rigorous: eras 0, 1, 2 are actual TM era entries, and none has a bad V. -/
example : eraND 0 = some (2, 4) := by native_decide
example : eraND 1 = some (5, 6) := by native_decide
example : eraND 2 = some (8, 8) := by native_decide
example : hasBadV 2 4 = false := by native_decide
example : hasBadV 5 6 = false := by native_decide
example : hasBadV 8 8 = false := by native_decide

/-!
### Arithmetic-sequence results (do NOT transfer to the TM for i ≥ 3)

The following facts are true **about the arithmetic sequence** `eraSeq`
generated by the current (heuristic) `nextEra`. They do NOT transfer
to the TM's actual trajectory for i ≥ 3, because the k=1 and k≥2
branches of `nextEra` are not faithful to the TM dynamics. See
`strategy.md` for the correction plan.
-/

/-- (About the arithmetic sequence only, for i ≥ 3) The first 21
    arithmetic era entries all have `hasBadV = false`. Verified by
    `native_decide`. Only eras 0–2 also correspond rigorously to the
    TM's trajectory. -/
example : ∀ i < 21, eraHasBadV i = false := by native_decide

/-- (About the arithmetic sequence) Era 21 is the first with
    `hasBadV = true` (at `n = 68, d = 46`). Under the uniform-V model
    `P(bad | reached era 21) ≤ 1/2^68 ≈ 3.4·10^-21`. -/
example : eraHasBadV 21 = true := by native_decide

/-- (About the arithmetic sequence) At era 21, `(n, d) = (68, 46)`. -/
example : eraND 21 = some (68, 46) := by native_decide

/-- The first 50 eras' `hasBadV` flags (for inspection). -/
def badFlags (N : Nat) : List (Nat × Bool) :=
  (List.range N).map (fun i => (i, eraHasBadV i))

-- #eval badFlags 30

-- ============================================================
-- §5. Cumulative bound on "ever hits bad"
-- ============================================================

/-- Upper bound on `P(era i is bad | reached era i)`: `1/2^{n_i}` if
    `hasBadV`, else `0`. -/
def eraProbBad (i : Nat) : Rat :=
  match eraND i with
  | some (n, d) => if hasBadV n d then (1 : Rat) / (2^n : Nat) else 0
  | none => 0

/-- Union bound: `P(ever bad in first N eras) ≤ Σ_{i<N} eraProbBad i`. -/
def cumBadUpper (N : Nat) : Rat :=
  (List.range N).foldl (fun acc i => acc + eraProbBad i) 0

-- Over the first 22 eras, only era 21 contributes (with 1/2^68).
-- #eval cumBadUpper 22  -- should print 1/2^68

-- ============================================================
-- §6. Caveats and interpretation
-- ============================================================

/-!
### Interpretation

The model above gives a probabilistic UPPER BOUND on how often the
(currently-heuristic) **arithmetic sequence** `eraSeq` would hit a bad
value if `V_i` were uniformly random. Caveats:

1. **`V_i` is deterministic**, not random. The probabilistic bound is not
   a proof — it's a sanity check on the arithmetic sequence.

2. **`hasBadV = false` for 21 consecutive eras** of `eraSeq` is a
   structural coincidence. Understanding WHY requires number-theoretic
   analysis (specifically, of the distribution of
   `{log_2(2^n + 3^d) mod 1}` across the sequence's `(n_i, d_i)`).

3. **Era 21 onwards**, some eras have `hasBadV = true` but the
   probability of actually hitting is `1/2^{n_i}` ≤ 1/2^68, astronomically small.

4. The sum `Σ_i eraProbBad i` is upper-bounded by
   `1/2^68 + 1/2^{n_{22}} + ...`, which converges rapidly (since `n_i`
   grows monotonically by at least 2 per era typically).

5. A fully-rigorous version would require:
   - Replacing `nextEra`'s heuristic k=1 and k≥2 branches with
     proved (and thus faithful) arithmetic transitions (see
     `strategy.md`'s "Plan for proving k≥2 dynamics").
   - Proving `hasBadV` truly rules out bad V's for the structural cases.
   - Characterizing the deterministic `V_i` modulo `2^{n_i}` to show it
     specifically avoids `badV(n_i, d_i)` at each era where the latter
     exists.

None of these is easy. Item (1) is EMPIRICALLY EVIDENT, item (4)
gives the expected flavor of the number-theoretic argument required,
and item (5) is the main technical dependency.
-/

end TM5.Prob
